# generated by Git for Windows
# Git bash profile for git shorthand 

# use "gc" insted of full "git checkout"  in git bash for windows or linus/mac terminal

# file located at type "cd ~" in cmd/gitbash
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
alias gc="git checkout"
alias gb="git branch"
alias gp="git pull"
alias gm="git merge"
alias gs="git status"
